"use client";

/**
 * Client-side report generation. PDFs via jsPDF, spreadsheets via SheetJS.
 * Running on-device keeps exports working offline from cached data and
 * avoids server-side font/bundling issues.
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { format } from "date-fns";

type Row = Record<string, string | number | null | undefined>;

const BRAND: [number, number, number] = [33, 92, 36];

function pdfHeader(doc: jsPDF, title: string, farmName: string, extra?: string) {
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 26, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text("KhulaGrow", 14, 11);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(title, 14, 19);

  doc.setTextColor(60, 60, 60);
  doc.setFontSize(9);
  doc.text(`Farm: ${farmName}`, 14, 34);
  doc.text(`Generated: ${format(new Date(), "d MMM yyyy HH:mm")}`, 14, 39);
  if (extra) doc.text(extra, 14, 44);
  return extra ? 50 : 45;
}

function pdfFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by KhulaGrow · SAHPRA record-keeping · Page ${i} of ${pages}`,
      14,
      doc.internal.pageSize.getHeight() - 8
    );
  }
}

export function exportTablePDF(opts: {
  filename: string;
  title: string;
  farmName: string;
  extra?: string;
  columns: string[];
  rows: (string | number)[][];
  summary?: string[];
}) {
  const doc = new jsPDF({ orientation: opts.columns.length > 6 ? "landscape" : "portrait" });
  let y = pdfHeader(doc, opts.title, opts.farmName, opts.extra);

  if (opts.summary?.length) {
    doc.setFontSize(9);
    doc.setTextColor(40, 40, 40);
    for (const line of opts.summary) {
      doc.text(line, 14, y);
      y += 5;
    }
    y += 2;
  }

  autoTable(doc, {
    startY: y,
    head: [opts.columns],
    body: opts.rows,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: BRAND, fontSize: 8 },
    alternateRowStyles: { fillColor: [246, 247, 244] },
  });

  pdfFooter(doc);
  doc.save(`${opts.filename}.pdf`);
}

export function exportExcel(opts: {
  filename: string;
  sheets: { name: string; rows: Row[] }[];
}) {
  const wb = XLSX.utils.book_new();
  for (const sheet of opts.sheets) {
    const ws = XLSX.utils.json_to_sheet(sheet.rows.length ? sheet.rows : [{ note: "No data" }]);
    // Reasonable column widths from content
    const keys = Object.keys(sheet.rows[0] ?? { note: 1 });
    ws["!cols"] = keys.map((k) => ({
      wch: Math.min(
        40,
        Math.max(k.length + 2, ...sheet.rows.map((r) => String(r[k] ?? "").length + 2))
      ),
    }));
    XLSX.utils.book_append_sheet(wb, ws, sheet.name.slice(0, 31));
  }
  XLSX.writeFile(wb, `${opts.filename}.xlsx`);
}

/** Multi-section investor/compliance portfolio PDF. */
export function exportPortfolioPDF(opts: {
  farmName: string;
  licence?: string | null;
  stats: { label: string; value: string }[];
  sections: { heading: string; columns: string[]; rows: (string | number)[][] }[];
}) {
  const doc = new jsPDF();
  let y = pdfHeader(
    doc,
    "Cultivation Portfolio",
    opts.farmName,
    opts.licence ? `SAHPRA licence: ${opts.licence}` : undefined
  );

  // Key stats grid
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND);
  doc.text("Key figures", 14, y + 4);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(40, 40, 40);
  opts.stats.forEach((s, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    doc.setFont("helvetica", "bold");
    doc.text(s.value, 14 + col * 95, y + row * 11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text(s.label, 14 + col * 95, y + row * 11 + 4);
    doc.setTextColor(40, 40, 40);
  });
  y += Math.ceil(opts.stats.length / 2) * 11 + 6;

  for (const section of opts.sections) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND);
    doc.text(section.heading, 14, y);
    autoTable(doc, {
      startY: y + 3,
      head: [section.columns],
      body: section.rows,
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: BRAND, fontSize: 8 },
      alternateRowStyles: { fillColor: [246, 247, 244] },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
  }

  pdfFooter(doc);
  doc.save(`${opts.farmName.replace(/\s+/g, "-").toLowerCase()}-portfolio.pdf`);
}
